# Generated by Django 5.2 on 2026-08-11 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todos_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
